services:
  # Backend API service
  - type: web
    name: ai-content-generation-api
    runtime: docker
    rootDir: backend/Ai-Content-Generation
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    buildCommand: ./mvnw clean package -DskipTests
