services:
  # Backend API service
  - type: web
    name: ai-content-generation-api
    runtime: docker
    rootDir: backend/Ai-Content-Generation
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      # Pass through environment variables from .env file
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    buildCommand: ./mvnw clean package -DskipTests
    envVarsFile: .env
